artifact_location: file:///C:/Users/Mani/OneDrive/Desktop/Storage_G/Backend/runs/mlflow/0
creation_time: 1763357169367
experiment_id: '0'
last_update_time: 1763357169367
lifecycle_stage: active
name: Default
