artifact_location: file:///C:/Users/Mani/OneDrive/Desktop/Storage_G/Backend/runs/mlflow/125836773239282251
creation_time: 1763357169411
experiment_id: '125836773239282251'
last_update_time: 1763357169411
lifecycle_stage: active
name: runs/agricultural_training
